### ISSUE TITLE
Flags are not languages, some other code should be preferrable

### ISSUE THREAD

**Issue by veikkoeeva** [GuOrg/Gu.Localization#10]
In section _7. LanguageSelector - A simple control for changing current language._ it is presented there is a flag indicating language selection. This choice is problematic, of which I'll include perhaps the most commonly distinquished one.

Having [a flag of Great Britain](http://flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/) doesn't mean English to people in general and it likely annoys some people. The linked site links other similar flag choice problems. One not listed is the Swedish speaking minority usually would not like to choose a Swedish flag for service in Swedish since they are Finns.

There are are plenty of resources with regards this problem domain in Internet and it may be difficult to decide which method to pick. Personally it looks to me [How to graphically represent a language](http://ux.stackexchange.com/questions/2472/how-to-graphically-represent-a-language) lists choices both graphically and textually.

On a larger context, it might make sense to support a larger spectrum of language codes than the two-letter IETF variant one usually sees being used. I mean if it would make sense to support [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) with wider languages as in for instance [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2), [CultureInfo.ThreeLetterISOLanguageName](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.threeletterisolanguagename%28v=vs.110%29.aspx). My very superficial knowledge leads me to believe some Microsoft products, such as Dynamix, has a somewhat extended support beyond what .NET supports (or adds support at a slower phase). It might make sense to introduce a clear point of variability at least if one wants to include ones own language.

**Comment by JohanLarsson** [comment]
Thanks for the issue!

**Comment by JohanLarsson** [comment]
Falling back to `CultureInfo.CreateSpecificCulture` for neutral cultures now.
Also there is always the option to use the `LanguageSelector` in manual mode:

```xml
<l:LanguageSelector>
  <l:Language Culture="sv-SE" FlagSource="pack://application:,,,/Gu.Wpf.Localization;component/Flags/se.png" />
  <l:Language Culture="en-GB" FlagSource="pack://application:,,,/Gu.Wpf.Localization;component/Flags/en.png" />
  <l:Language Culture="de-DE" FlagSource="pack://application:,,,/Gu.Wpf.Localization;component/Flags/de.png" />
  <l:Language Culture="fi-FI" FlagSource="pack://application:,,,/Gu.Wpf.Localization;component/Flags/fi.png" />
</l:LanguageSelector>
```

Also for the general case text only is probably nicer.
