### ISSUE TITLE
Intellisenece not work

### ISSUE THREAD

**Issue by ghost1372** [GuOrg/Gu.Localization#118]
why Intellisenece not work? i cant see StaticExtension and other markup

![Untitled](https://user-images.githubusercontent.com/9213496/112621523-7b74b380-8e47-11eb-96af-60952ee33260.png)

**Comment by ghost1372** [comment]
@JohanLarsson  i removed `[MarkupExtensionReturnType(typeof(BindingExpression))]` from StaticExtension and now Intellisenece work fine, Will there be a problem later?

**Comment by JohanLarsson** [comment]
I don't think that will break anything, only used by tooling IIRC.
