### ISSUE TITLE
How to Change DesignTime Culture?

### ISSUE THREAD

**Issue by ghost1372** [GuOrg/Gu.Localization#119]
I used a AttachedProperty but it doesn't seem to work, so How to Change DesignTime Culture?
```
 xmlns:l="http://gu.se/Localization"
        l:DesignTime.Culture="en">
```

**Comment by ghost1372** [comment]
i changed `UIElement ` to `DependencyObject` and removed `AttachedPropertyBrowsableForType`
now everything work fine

**Comment by zhaoyipeng** [comment]
Can you please give an example for designtime culture
