### ISSUE TITLE
set Resource with AttachedProperty

### ISSUE THREAD

**Issue by ghost1372** [GuOrg/Gu.Localization#120]
It's annoying to write the resource name every time

`Text="{l:Static local:Resource.Key"}`

so It is best to specify the resource name by AttachedProperty.
Therefore, localization will be easier

```
<window:
ResxName="local:Resource"/>

```
`Text="{l:Static Key"}`

@JohanLarsson Can you consider it?

**Comment by JohanLarsson** [comment]
Not sure how this would work with tooling. Getting autocompletion and compiler checks of the resource name is useful.
