### ISSUE TITLE
Is it possible to use converter in xaml with StaticExtension?

### ISSUE THREAD

**Issue by alex-buraykin** [GuOrg/Gu.Localization#86]

**Comment by JohanLarsson** [comment]
You can probably hack it using Binding.Source.

**Comment by Genusatplay** [comment]
if i use binding like this
`<TextBlock Text="{Binding Source={l:Static p:Resources.UserFiles}, Converter={converters:StringToUpperConverter}}"/>`
in runtime it return "#USERFILES#"
but in xaml designer ist look right "USER FILES"

**Comment by JohanLarsson** [comment]
I'll try to repro

**Comment by JohanLarsson** [comment]
Thank you for reporting, we were not handling this case well.
Added a fix and updated documentation. https://github.com/GuOrg/Gu.Localization#with-converter

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Wpf.Localization/6.7.0

**Comment by Genusatplay** [comment]
Translate with converter works good, but in designer text not showing.
Resharper says "Cannot resolve property 'Translated' in data context of type 'string'".

**Comment by JohanLarsson** [comment]
Can you create a new issue about the text not showing in the designer?
Most likely there is not much we can do about it, the designer is special.

About ReSharper I don't know how it fi8gues out `string` but I think it involves a bit of guessing. You can create an issue about this also and maybe we can figure it out some day.
