### ISSUE TITLE
Feature request: create an event that fires when a translation is missing

### ISSUE THREAD

**Issue by gverbake** [GuOrg/Gu.Localization#88]
Use case: logging of missing keys
Could be integrated with ErrorHandling: new option: FireEvent

**Comment by JohanLarsson** [comment]
Sounds reasonable, do you have API ideas?

**Comment by gverbake** [comment]
@JohanLarsson Thanks, will check it out in our usecase!

**Comment by JohanLarsson** [comment]
I should have made a PR for review but rushed things.
